# 11 数据合并(pd.concat)

In [2]:
import pandas as pd
import numpy as np
# np里边的合并
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)
print('-'*50)
print(np.concatenate([arr1, arr2])) #行数变多
print('-'*50)
print(np.concatenate([arr1, arr2], axis=1))

[[8 6 8 0]
 [5 5 3 9]
 [7 0 0 2]]
[[3 7 5 7]
 [8 9 3 9]
 [0 0 6 3]]
--------------------------------------------------
[[8 6 8 0]
 [5 5 3 9]
 [7 0 0 2]
 [3 7 5 7]
 [8 9 3 9]
 [0 0 6 3]]
--------------------------------------------------
[[8 6 8 0 3 7 5 7]
 [5 5 3 9 8 9 3 9]
 [7 0 0 2 0 0 6 3]]


In [3]:
# index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    7
1    0
2    3
3    5
4    2
dtype: int32
5    1
6    9
7    0
8    3
dtype: int32
9     3
10    4
11    9
dtype: int32


In [4]:
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))
print('-'*50)
print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1))

0     7
1     0
2     3
3     5
4     2
5     1
6     9
7     0
8     3
9     3
10    4
11    9
dtype: int32
--------------------------------------------------
      0    1    2
0   7.0  NaN  NaN
1   0.0  NaN  NaN
2   3.0  NaN  NaN
3   5.0  NaN  NaN
4   2.0  NaN  NaN
5   NaN  1.0  NaN
6   NaN  9.0  NaN
7   NaN  0.0  NaN
8   NaN  3.0  NaN
9   NaN  NaN  3.0
10  NaN  NaN  4.0
11  NaN  NaN  9.0


### index 有重复的情况

In [5]:
# index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    2
1    3
2    3
3    6
4    4
dtype: int32
0    6
1    9
2    6
3    2
dtype: int32
0    2
1    4
2    1
dtype: int32


In [6]:
#相同索引名直接往下排
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))

0    2
1    3
2    3
3    6
4    4
0    6
1    9
2    6
3    2
0    2
1    4
2    1
dtype: int32


In [8]:
#inner 和outer 代表内连接和全外连接,分为这两种
print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1, join='outer'))

   0    1    2
0  2  6.0  2.0
1  3  9.0  4.0
2  3  6.0  1.0
3  6  2.0  NaN
4  4  NaN  NaN


练习df的concat

In [9]:
#df的concat
import pandas as pd
import numpy as np
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['A', 'B'])
print(df_obj1)
print(df_obj2)
print('-'*50)
print(pd.concat([df_obj1, df_obj2]))
print('-'*50)
print(pd.concat([df_obj1, df_obj2], axis=1))

   A  B
a  2  5
b  1  6
c  0  3
   A  B
a  2  4
b  1  7
--------------------------------------------------
   A  B
a  2  5
b  1  6
c  0  3
a  2  4
b  1  7
--------------------------------------------------
   A  B    A    B
a  2  5  2.0  4.0
b  1  6  1.0  7.0
c  0  3  NaN  NaN


### 11.3 数据重构

In [11]:
df_obj = pd.DataFrame(np.random.randint(0,10, (5,2)), columns=['data1', 'data2'])
print(df_obj)
#对df进行stack，就会变成mutiindex的series
stacked = df_obj.stack()  #stack内部带的参数level，选择哪一个column变为index
print('-'*50)
print(stacked) #会变成mutiindex的series

   data1  data2
0      7      4
1      8      1
2      4      5
3      6      9
4      2      7
--------------------------------------------------
0  data1    7
   data2    4
1  data1    8
   data2    1
2  data1    4
   data2    5
3  data1    6
   data2    9
4  data1    2
   data2    7
dtype: int32


In [12]:
# 默认操作内层索引
print(stacked.unstack())
print('-'*50)
# 通过level指定操作索引的级别
print(stacked.unstack(level=0))

   data1  data2
0      7      4
1      8      1
2      4      5
3      6      9
4      2      7
--------------------------------------------------
       0  1  2  3  4
data1  7  8  4  6  2
data2  4  1  5  9  7


In [13]:
#stack和unstack对df操作
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])

df= pd.DataFrame(np.arange(24).reshape(12,2),index=index1,columns=['data1','data2'])
print(df)
df_s=df.unstack(level=0)  #把行索引中的一个级别拿到列索引
print('-'*50)
print(df_s)
print('-'*50)
print(df_s.columns) #看到columns索引变为层级索引
print('-'*50)
df_s.stack(0)  #把columns上的0层索引放到index的内层索引

            data1  data2
cloth size              
a     0         0      1
      1         2      3
      2         4      5
b     0         6      7
      1         8      9
      2        10     11
c     0        12     13
      1        14     15
      2        16     17
d     0        18     19
      1        20     21
      2        22     23
--------------------------------------------------
      data1             data2            
cloth     a   b   c   d     a   b   c   d
size                                     
0         0   6  12  18     1   7  13  19
1         2   8  14  20     3   9  15  21
2         4  10  16  22     5  11  17  23
--------------------------------------------------
MultiIndex([('data1', 'a'),
            ('data1', 'b'),
            ('data1', 'c'),
            ('data1', 'd'),
            ('data2', 'a'),
            ('data2', 'b'),
            ('data2', 'c'),
            ('data2', 'd')],
           names=[None, 'cloth'])
-------------------------------------

cloth       a   b   c   d
size                     
0    data1  0   6  12  18
     data2  1   7  13  19
1    data1  2   8  14  20
     data2  3   9  15  21
2    data1  4  10  16  22
     data2  5  11  17  23

 ## 11.4 处理重复数据

In [15]:
df_obj = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})
print(df_obj)

  data1  data2
0     a      2
1     a      1
2     a      1
3     a      3
4     b      0
5     b      1
6     b      3
7     b      3


In [16]:
print(df_obj.duplicated())
print('-'*50)
df_obj[~df_obj.duplicated()]  #取出不重复行

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
dtype: bool
--------------------------------------------------


data1  data2
0     a      2
1     a      1
3     a      3
4     b      0
5     b      1
6     b      3

In [17]:
#按照某一列去重
print(df_obj.duplicated('data2'))

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7     True
dtype: bool


In [22]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1335')})
df_obj1

data1 data2
0    NaN     1
1    NaN     3
2    NaN     3
3    NaN     5

In [24]:
#在pd的duplicated认为空值和空值是重复的
print(df_obj1.duplicated('data1'))
print('-'*50)
print(df_obj1.drop_duplicates('data1'))

0    False
1     True
2     True
3     True
dtype: bool
--------------------------------------------------
   data1 data2
0    NaN     1


In [25]:
print(df_obj.drop_duplicates())  #删除重复行
print(df_obj.drop_duplicates('data2'))

  data1  data2
0     a      2
1     a      1
3     a      3
4     b      0
5     b      1
6     b      3
  data1  data2
0     a      2
1     a      1
3     a      3
4     b      0


In [26]:
#如果要在原有的df上去重，需要加inplace=True
df_obj

data1  data2
0     a      2
1     a      1
2     a      1
3     a      3
4     b      0
5     b      1
6     b      3
7     b      3

In [27]:
ser_obj = pd.Series(np.random.randint(0,10,10))  #series 用map
print(ser_obj)

print(ser_obj.map(lambda x : x ** 2))

0    4
1    7
2    7
3    2
4    1
5    6
6    1
7    1
8    0
9    2
dtype: int32
0    16
1    49
2    49
3     4
4     1
5    36
6     1
7     1
8     0
9     4
dtype: int64


In [28]:
ser_obj=pd.Series(np.arange(10),index=range(3,13))
# 单个值替换单个值
print(ser_obj.replace(1, -100))

# 多个值替换一个值
print(ser_obj.replace(range(6,9), -100))

# 多个值替换多个值
print(ser_obj.replace([4, 7], [-100, -200]))

3       0
4    -100
5       2
6       3
7       4
8       5
9       6
10      7
11      8
12      9
dtype: int32
3       0
4       1
5       2
6       3
7       4
8       5
9    -100
10   -100
11   -100
12      9
dtype: int32
3       0
4       1
5       2
6       3
7    -100
8       5
9       6
10   -200
11      8
12      9
dtype: int32


In [29]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})

In [ ]:
df

In [31]:
df.replace(to_replace=r'[a-c]', value=100, regex=True)

A  B    C
0  0  5  100
1  1  6  100
2  2  7  100
3  3  8    d
4  4  9    e

In [ ]:
df.dtypes

In [ ]:
print('hello')